### ISSUE TITLE
Does this work behind a reverse proxy "Nginx"?

### ISSUE THREAD

**Issue by chanlito** [uqee/sticky-cluster#18]
I'm using Express, socket.io, and socket.io-redis.

**Comment by uqee** [comment]
Yes, you just need to set your nginx to [transparent mode](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html#proxy_bind).

**Comment by BruceHem** [comment]
doesn't seem to work getting the following:

2017/05/04 15:12:47 [alert] 27654#27654: *63 setsockopt(IP_TRANSPARENT) failed (1: Operation not permitted) while connecting to upstream, client: 115.178.26.226, server: apidev.tesjor.com, request: "GET /socket.io/?EIO=3&device_id=48f3688eec71e656&client_id=4be8674673d0438e9601d0120466118e&hash=1984be815bba4014bfdbb7ee1edeee7d&transport=polling HTTP/1.1", upstream: "http://127.0.0.1:3000/socket.io/?EIO=3&device_id=48f3688eec71e656&client_id=4be8674673d0438e9601d0120466118e&hash=1984be815bba4014bfdbb7ee1edeee7d&transport=polling", host: "apidev.tesjor.com"

**Comment by uqee** [comment]
Honestly, seems like you have issues with nginx config. Sticky-cluster only needs original IP addresses to work properly. You just need to configure your proxy to achieve this.

**Comment by sam2x** [comment]
Please provide us a way to set the client IP to be used (either by default, or by x-forwarded-for, or by custom callback). I dont want to make change on my server and my proxy. Setting a proxy as transparent requires to modify the configuration of the proxy-server AND the backend server (mangle route at kernel so it forwards them...), plus it brings some more load. 
I guess it's this part that need to be modified https://github.com/uqee/sticky-cluster/blob/master/lib/master.js#L13

**Comment by uqee** [comment]
x-forwarded-for would work for you?

**Comment by uqee** [comment]
i don't see any actual use case for a callback support. if you do, please provide one.

**Comment by sam2x** [comment]
Yes in my express env  x-forwarded-for or real-ip will work, because i'm setting app.enable('trust proxy')! But, for security reason, it should be specified by user and not automatically picked/guessed by code, so we could just add a configuration parameter like: 

     {
       concurrency: 10,
       port: 3000,
       debug: true,
       'customRemoteAddress':'x-forwarded-for' 
     }
 
If 'customRemoteAddress' specified, the ip is not taken from connection.remoteAddress but from http header. What do you think ?
The callback support way was to avoid you to write code, and let user fetch the ip. Example : 

      {
       concurrency: 10,
       port: 3000,
       debug: true,
       customRemoteAddress: function(req, cb) {
         cb (req.headers['x-forwarded-for'])
       }
    }

**Comment by uqee** [comment]
Sorry, I forgot about one important thing: master process creates a TCP proxy server and it pauses socket reading before any HTTP data is being read (e.g. headers in this case). Only the chosen client resumes the reading process and actually parses HTTP headers. So, we can only use parameters from a [net.Socket](https://nodejs.org/api/net.html#net_class_net_socket) instance to figure out what to do.

**Comment by sam2x** [comment]
Ho... it operates at transport layer and not application layer..

**Comment by sam2x** [comment]
Indeed, we cant solve this way... And adding a parsing layer to your lib is really a bad idea, since it will significantly impact the perf...

Interesting response from Tomty about this here : 
 https://stackoverflow.com/questions/30706420/get-client-ip-of-the-request-in-net-library-nodejs 

~~Do you have any feedbacks/recommandations about which sticky session lib to use that is doing same things as your lib without the "balancer" feature (and has decent benchmark), so i can fork & maps my nodejs app to N ports, and let nginx decide which port to use according the source ip ?~~

**Comment by sam2x** [comment]
Ok got a solution Tomty answer.

For those having the same env as me, and so this problem, here explanation  : 

1. Modify your code [See Tomty answer](https://stackoverflow.com/a/34803809), so it binds to X differents ports based on process.env.port (be careful if you map X port according to your server's number of core, since you'll need to update nginx conf each time your server change). So we got something like that : 

```
if (cluster.isMaster) 
{
    var STARTING_PORT = XXXX;
    var NUMBER_OF_WORKERS = XX;
    var pidToPort = {}; 
    var worker = null;
    for (var i = 0; i < NUMBER_OF_WORKERS; i++) {
        var p = STARTING_PORT + i;
        worker = cluster.fork({ port: p});
        pidToPort[worker.process.pid] = p;
    }

    cluster.on('exit', function(worker, code, signal) {
        /* is it called when process is legitimately killed ? */
        var w = null;
        var p = pidToPort[worker.process.pid];
        w = cluster.fork({port: p});
        pidToPort[w.process.pid] = p;
        delete pidToPort[worker.process.pid];
    });
}
else {...}
```

2. Be sure that nginx has 'ip_hash' [load balancing method](http://nginx.org/en/docs/http/load_balancing.html), so the same source ip will always be redirected to the same port (very important for socket.io ).
3. Set an upstream block and simple proxy conf  : 
```
 upstream myapp1 {
        ip_hash;
        server app:10000;
        server app:10001;
        server app:10002;
        [...etc]
    }
   [...]
        location /myapp {
            proxy_pass http://myapp1;
        }
   }
```
Ipv6 is not a concern, since in my case, it's the front proxy who handle this (and i use ipv4 in my internal network) :

[client] --- (ipv4/ipv6) ---- [nginx] -----(ipv4)|--- app_instance_1
..................................................................|--- app_instance_X

Thx for your support @uqee .

**Comment by uqee** [comment]
Do you mean like [cluster](https://github.com/LearnBoost/cluster)?
