### ISSUE TITLE
Load balancing

### ISSUE THREAD

**Issue by ghost** [uqee/sticky-cluster#2]
Seeing this is pretty similar to the sticky-session module, I'd like to ask the same question like I did there (#41), is load balancing possible (through the XFF header or other means)?

**Comment by uqee** [comment]
Hi, @Xaxatix!
The main goal of this module is to map multiple requests from one client to the same worker process no matter how busy it is. This idea contradicts any kind of a load balancer though.

**Comment by ghost** [comment]
Well, the idea of the cluster module is to make better use of the system's resources, but that happens only on a single system. If you were to expand it to multiple, you have to add another layer of load balancing. But the problem comes from the fact that intra cluster sticky sessions don't play nice with reverse proxies/load balances, because the remoteAddress remains the same, so all traffic will always get routed to only one of the workers.

**Comment by uqee** [comment]
Yep, I understood. Again, if your app works fine with load balancing than you simply don't need neither this module nor the `sticky-session` one, have a look at the detailed explanation of one of the use cases: [why does `socket.io` need sticky sessions](http://socket.io/docs/using-multiple-nodes/).

Although, if you still think you do, then it means you want to implement sticky (not load-based) routing on your proxy and sticky sessions on every machine inside (horizontal and vertical scaling at once). In that case, your master process has to start reading a socket to get `XFF` header to determine the corresponding worker, but the latter supposes it also starts reading from the beginning. I'm sure this problem is solvable, but if I were you, I'd consider other options.

**Comment by ghost** [comment]
Yes, but not using clustering on a multi core machine would mean that you'd have to run your app multiple times and on different ports, which is kinda cumbersome if you ask me. But if you run in cluster mode, sticky sessions is required. So in reality to achieve true horizontal (multiple servers) and vertical (cluster per server) scaling, you'd need a sticky reverse proxy for the horizontal scalability part, and then another sticky reverse proxy in the master cluster process for the vertical scaling. Don't know if it's worth the trouble and most importantly performance loss to go this far just for `socket.io`.
