### ISSUE TITLE
Does not take into account Connections received through Load balancers like haproxy

### ISSUE THREAD

**Issue by more456** [uqee/sticky-cluster#21]
This uses connection.remoteaddress which provides always LB ip and not the client IP. Since this is based on node NET module, not able to find how to set this to forwarded-for client IP or any other way without changing the basic way of starting connection.

**Comment by glanceded** [comment]
Yes, it would be nice a setting like: 

(bool) $trustProxy = true;
and take the last ip inline as the valid one / end user.

**Comment by elithrar** [comment]
This library doesn't operate at L7 (HTTP), only at L4 - see https://github.com/uqee/sticky-cluster/blob/master/lib/master.js#L9-L16

In order to use X-Forwarded-For or some other HTTP header, you would need to change this. You could just create a small module that uses `http.Server` and has an event handler for the `request` event that can do this instead - e.g.

```ts
  let app = express()
  let server = http.createServer(app)

  server.on("request", (req: http.IncomingMessage, res: http.ServerResponse) => {
        // Inspect req.headers as needed
    })
```

**Comment by uqee** [comment]
Unfortunately, it's not possible. Have a look at [#18](https://github.com/uqee/sticky-cluster/issues/18). One possible solution is also discussed there.
