### ISSUE TITLE
Does this work on a PaaS like Heroku?

### ISSUE THREAD

**Issue by HoukasaurusRex** [uqee/sticky-cluster#38]
I'm using Express with socket.io, and socket.io-redis.
I can connect fine to a single worker on localhost, but on production (my code is hosted on Heroku), my clients fail to poll the server. 

On chrome the output is:

> socket.io.js:7 WebSocket connection to 'wss://www.domain.com/socket.io/?EIO=3&transport=websocket&sid=dii-cKddDjTJA0ibAABI' failed: Error during WebSocket handshake: Unexpected response code: 400

and in Firefox:

> Firefox can’t establish a connection to the server at wss://www.domain.com/socket.io/?EIO=3&transport=websocket&sid=doqp432PNelmMmPzAADP.

I'm wondering if this issue is something related to Heroku, or if localhost was only working because all clients were sent to the same worker (same IP) and I'm just missing something simple?
Thanks a lot in advance

**Comment by uqee** [comment]
Hi, @Pterobyte thanks for the question!

I guess not, because to delegate connections based on some principle we should have a "proxy" (master process) and a bunch of children (worker processes). At the same time Heroku has its own concept of [`dynos`](https://www.heroku.com/dynos), managed automatically by the internal scaling system, so it probably disallows any process forks inside a `dyno`. Even if it was allowed, it would mean only one `dyno` should be used, which limits to vertical scaling only.

If I'm not mistaken, you don't need `sticky-cluster` on Heroku at all, because they have their own concept named [session affinity](https://devcenter.heroku.com/articles/session-affinity), please, have a look.
